@extends('layouts.admin')

@section('title', 'Buat Turnamen')

@section('content')
<div class="page-header">
    <div class="page-header-content">
        <div style="flex: 1;">
            <div class="page-title">
                <div class="page-title-icon">
                    <i data-feather="plus-square"></i>
                </div>
                <div>
                    <span>Buat Turnamen Baru</span>
                    <div class="page-subtitle">Setup nama turnamen dan daftar tim peserta</div>
                </div>
            </div>
        </div>
        <a href="{{ route('admin.tournaments.index') }}" class="btn btn-secondary">
            <i data-feather="arrow-left"></i>
            Kembali
        </a>
    </div>
</div>

<form action="{{ route('admin.tournaments.store') }}" method="POST">
    @csrf
    <div class="content-grid">
        <!-- Configuration -->
        <div class="card">
            <div class="card-header" style="background: linear-gradient(135deg, var(--primary) 0%, var(--primary-dark) 100%); color: white; border-bottom: none;">
                <div class="card-title" style="color: white;">
                    <i data-feather="award"></i> Informasi Turnamen
                </div>
            </div>
            <div class="card-body">
                <div class="form-group">
                    <label class="form-label">Nama Turnamen</label>
                    <input type="text" name="title" class="form-control" placeholder="Contoh: Class Meeting Semester 1" required>
                </div>

                <div class="form-group">
                    <label class="form-label">Deskripsi (Opsional)</label>
                    <textarea name="description" class="form-control" style="min-height: 80px;" placeholder="Catatan tambahan..."></textarea>
                </div>

                <div class="alert alert-info" style="margin-top: 1rem; background: rgba(59, 130, 246, 0.1); border: 1px solid rgba(59, 130, 246, 0.3); border-radius: var(--radius-md); padding: 1rem;">
                    <div style="display: flex; align-items: flex-start; gap: 0.75rem;">
                        <i data-feather="info" style="width: 20px; min-width: 20px; color: var(--accent-blue);"></i>
                        <div>
                            <strong style="color: var(--primary-dark);">Catatan:</strong>
                            <p style="margin: 0.5rem 0 0 0; color: var(--gray); font-size: 0.9rem;">
                                Konfigurasi soal (topik, materi, jumlah soal, waktu) akan diatur <strong>per pertandingan</strong> setelah bagan dibuat. Ini memungkinkan setiap match memiliki soal berbeda untuk mencegah siswa menghafalkan jawaban.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Team Setup -->
        <div class="card">
            <div class="card-header" style="background: linear-gradient(135deg, var(--primary) 0%, var(--primary-dark) 100%); color: white; border-bottom: none;">
                <div class="card-title" style="color: white;">
                    <i data-feather="users"></i> Daftar Tim
                </div>
                <div class="badge badge-blue" id="teamCountBadge" style="background: rgba(255,255,255,0.2); color: white;">4 Tim</div>
            </div>
            <div class="card-body">
                <div class="form-group">
                    <label class="form-label">Jumlah Tim (3-16)</label>
                    <div style="display: flex; align-items: center; gap: 1rem;">
                        <input type="number" id="teamCountInput" class="form-control" style="width: 100px;" value="4" min="3" max="16" onchange="generateTeamInputs()" onkeyup="generateTeamInputs()">
                        <div class="badge badge-purple" id="bracketPredictionBadge">
                            <i data-feather="info" style="width: 12px; height: 12px; margin-right: 4px;"></i>
                            Format: 4 Besar (Tanpa Bye)
                        </div>
                    </div>
                </div>

                <label class="form-label">Nama Tim</label>
                <div id="teamNameContainer" style="display: flex; flex-direction: column; gap: 0.75rem;">
                    <!-- Inputs generated by JS -->
                </div>
            </div>
        </div>
    </div>

    <div style="margin-top: 2rem; text-align: right;">
        <button type="submit" class="btn btn-primary btn-lg" style="padding: 1rem 3rem;">
            <i data-feather="check-circle"></i>
            Generate Bagan Turnamen
        </button>
    </div>
</form>

@push('scripts')
<script>
    // Handle Team Inputs
    function generateTeamInputs() {
        const input = document.getElementById('teamCountInput');
        let count = parseInt(input.value);
        
        // Boundaries
        if(isNaN(count)) count = 0;
        if(count > 16) count = 16; 
        
        const container = document.getElementById('teamNameContainer');
        const badge = document.getElementById('teamCountBadge');
        const predictionBadge = document.getElementById('bracketPredictionBadge');
        
        badge.textContent = count + ' Tim';
        
        // Calculate bracket size
        let bracketSize = 4;
        if (count > 8) bracketSize = 16;
        else if (count > 4) bracketSize = 8;
        
        const byes = bracketSize - count;
        if (byes === 0) {
             predictionBadge.innerHTML = `<i data-feather="grid" style="width:12px;height:12px;margin-right:4px;"></i> Format: ${bracketSize} Besar (Full)`;
             predictionBadge.className = 'badge badge-green';
        } else {
             predictionBadge.innerHTML = `<i data-feather="git-merge" style="width:12px;height:12px;margin-right:4px;"></i> Format: ${bracketSize} Besar (${byes} Tim mendapat Bye)`;
             predictionBadge.className = 'badge badge-purple';
        }
        
        // Save current values
        const currentValues = [];
        const existingInputs = document.getElementsByName('team_names[]');
        existingInputs.forEach(inp => currentValues.push(inp.value));
        
        container.innerHTML = '';
        
        if (count < 3) return; // Wait for valid input
        
        for(let i = 1; i <= count; i++) {
            const div = document.createElement('div');
            div.className = 'd-flex align-center gap-2';
            
            const val = currentValues[i-1] || `Tim ${i}`;
            
            div.innerHTML = `
                <div style="width: 30px; height: 30px; background: var(--cream); border-radius: 50%; display: flex; align-items: center; justify-content: center; font-weight: bold; color: var(--gray); font-size: 0.8rem;">${i}</div>
                <input type="text" name="team_names[]" class="form-control" placeholder="Nama Tim ${i}" value="${val}" required>
            `;
            container.appendChild(div);
        }
        
        if(typeof feather !== 'undefined') feather.replace();
    }

    // Init
    generateTeamInputs();
</script>
@endpush
@endsection
